### PR TITLE
update the constraints

### PR DESCRIPTION
**Pull request by beauZh**
update the collectionview and emptyview's bottom constraints

### CODE REVIEW

**Review by Grokthol — COMMENTED** [review]
I'm not seeing any real changes  here 🤔

**Comment by Grokthol** [comment]
Was it only constraint changes required?

**Comment by sadlerjw** [comment]
Yup!

**Review by sadlerjw — CHANGES_REQUESTED** [review]
We shouldn't be checking in the xcshareddata files

**Comment by sadlerjw** [comment]
Once this is done let's also submit the fix back to the developer with more information on what we did.

**Review by sadlerjw — APPROVED** [review]

**Pull request closed without merging**
